<img src="./images/banner.png" width="800">

# Indexing and Slicing Arrays

In this section, we'll introduce the concepts of indexing and slicing in NumPy arrays. These techniques allow you to access specific elements or subsets of an array efficiently. Let's dive in and understand what indexing and slicing mean in the context of NumPy.


**Indexing** refers to the process of accessing individual elements of an array using their positions or indices. In NumPy, arrays are zero-indexed, meaning that the first element has an index of 0, the second element has an index of 1, and so on.


To access an element in a NumPy array, you use square bracket notation `[]` and provide the index or indices of the desired element. For example, consider the following array:


In [1]:
import numpy as np

arr = np.array([10, 20, 30, 40, 50])

To access the first element of `arr`, you would use `arr[0]`, which returns `10`. Similarly, `arr[2]` would give you `30`, and so on.


In [2]:
arr[0]

10

In [3]:
arr[2]

30

Indexing allows you to retrieve specific elements from an array based on their positions, enabling you to work with individual values efficiently.


**Slicing** is the process of extracting a subset of elements from an array. It allows you to select a contiguous sequence of elements by specifying a range of indices. Slicing is performed using the colon (`:`) notation within square brackets `[]`.


The general syntax for slicing is `start:end:step`, where:
- `start` is the starting index (inclusive) of the slice.
- `end` is the ending index (exclusive) of the slice.
- `step` is the step size or stride, indicating the increment between each element in the slice.


Let's consider an example to understand slicing:


In [4]:
arr = np.array([10, 20, 30, 40, 50])

To extract a slice from `arr` that includes elements from index 1 to index 3 (exclusive), you would use `arr[1:4]`, which returns `[20, 30, 40]`.


In [5]:
arr[1:4]

array([20, 30, 40])

If you omit the `start` index, it defaults to 0 (the beginning of the array). If you omit the `end` index, it defaults to the length of the array. For example, `arr[:3]` would give you `[10, 20, 30]`, and `arr[2:]` would give you `[30, 40, 50]`.


In [6]:
arr[2:]

array([30, 40, 50])

In [7]:
arr[:3]

array([10, 20, 30])

You can also specify a step size to skip elements within the slice. For example, `arr[0:5:2]` would return `[10, 30, 50]`, selecting every second element from index 0 to index 4.


Slicing allows you to extract portions of an array efficiently, providing a concise way to work with subsets of data.


In the following sections, we'll explore indexing and slicing in more detail, covering their usage in single-dimensional and multi-dimensional arrays, as well as advanced techniques and practical examples.

**Table of contents**<a id='toc0_'></a>    
- [Indexing NumPy Arrays](#toc1_)    
  - [Accessing Elements using Square Bracket Notation](#toc1_1_)    
  - [Accessing Elements in Multi-dimensional Arrays](#toc1_2_)    
  - [Using Negative Indices](#toc1_3_)    
- [Slicing NumPy Arrays](#toc2_)    
  - [Basic Slicing Syntax](#toc2_1_)    
  - [Slicing Single-dimensional Arrays](#toc2_2_)    
  - [Slicing Multi-dimensional Arrays](#toc2_3_)    
  - [Slicing with Step Size](#toc2_4_)    
- [Advanced Indexing Techniques](#toc3_)    
  - [Boolean Indexing](#toc3_1_)    
  - [Fancy Indexing](#toc3_2_)    
  - [Combining Indexing and Slicing](#toc3_3_)    
- [Modifying Arrays using Indexing and Slicing](#toc4_)    
  - [Assigning Values to Array Elements](#toc4_1_)    
  - [Modifying Slices of an Array](#toc4_2_)    
  - [Views vs. Copies in Slicing](#toc4_3_)    
    - [Views](#toc4_3_1_)    
    - [Copies](#toc4_3_2_)    
  - [Memory Sharing Check](#toc4_4_)    
    - [When to Use Views vs. Copies](#toc4_4_1_)    
- [Best Practices and Common Pitfalls](#toc5_)    
  - [Avoiding Out-of-Bounds Errors](#toc5_1_)    
  - [Understanding View vs. Copy Behavior](#toc5_2_)    
  - [Performance Considerations](#toc5_3_)    
- [Practice Exercise: Analyzing Temperature Data](#toc6_)    
  - [Solution](#toc6_1_)    

<!-- vscode-jupyter-toc-config
	numbering=false
	anchor=true
	flat=false
	minLevel=2
	maxLevel=6
	/vscode-jupyter-toc-config -->
<!-- THIS CELL WILL BE REPLACED ON TOC UPDATE. DO NOT WRITE YOUR TEXT IN THIS CELL -->

## <a id='toc1_'></a>[Indexing NumPy Arrays](#toc0_)

Indexing is a fundamental operation in NumPy that allows you to access individual elements or subsets of an array. In this section, we'll explore different ways to index NumPy arrays using square bracket notation, access elements in multi-dimensional arrays, and use negative indices.


<img src="./images/indexing.png" width="800">

### <a id='toc1_1_'></a>[Accessing Elements using Square Bracket Notation](#toc0_)


To access elements in a NumPy array, you use square bracket notation `[]` followed by the index or indices of the desired element. Let's consider an example:


In [8]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

To access the first element of `arr`, you would use:


In [9]:
arr[0]

10

Similarly, to access the third element, you would use:


In [10]:
arr[2]

30

You can also use variables or expressions inside the square brackets:


In [11]:
index = 1
arr[index]

20

Using square bracket notation, you can easily access individual elements of a NumPy array by providing their indices.


### <a id='toc1_2_'></a>[Accessing Elements in Multi-dimensional Arrays](#toc0_)


In multi-dimensional arrays, you need to provide multiple indices to access elements. Each index corresponds to a specific dimension of the array. Let's consider a 2-dimensional array:


<img src="./images/numpy-slicing.png" width="800">

In [12]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To access an element in a 2-dimensional array, you provide the row index followed by the column index:


In [13]:
arr_2d[1, 2]  # Accesses the element at row 1 and column 2


6

In this example, `element` would be `6`.


You can also use separate square brackets for each dimension:


In [14]:
arr_2d[1][2]  # Equivalent to arr_2d[1, 2]

6

For higher-dimensional arrays, you simply provide more indices, one for each dimension.


### <a id='toc1_3_'></a>[Using Negative Indices](#toc0_)


In NumPy, you can use negative indices to access elements from the end of an array. The last element of an array has an index of -1, the second-to-last element has an index of -2, and so on. Let's consider an example:


In [15]:
arr = np.array([10, 20, 30, 40, 50])
arr

array([10, 20, 30, 40, 50])

To access the last element of `arr`, you would use:


In [16]:
arr[-1]

50

Similarly, to access the second-to-last element, you would use:


In [17]:
arr[-2]

40

Negative indexing allows you to access elements from the end of an array without knowing its exact length.


You can also use negative indices in multi-dimensional arrays:


In [18]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

To access the last element in the second row, you would use:


In [19]:
arr_2d[1, -1]

6

Negative indexing provides a convenient way to access elements from the end of an array, making it easier to work with arrays without explicitly calculating their lengths.


In the next section, we'll explore slicing NumPy arrays, which allows you to extract subsets of elements efficiently.

## <a id='toc2_'></a>[Slicing NumPy Arrays](#toc0_)

Slicing is a powerful feature in NumPy that allows you to extract subsets of elements from an array. It provides a concise and efficient way to access contiguous sections of an array. In this section, we'll explore the basic slicing syntax and how to slice single-dimensional and multi-dimensional arrays, as well as how to use step size in slicing.


<img src="./images/numpy-slicing.png" width="800">

### <a id='toc2_1_'></a>[Basic Slicing Syntax](#toc0_)


The basic syntax for slicing a NumPy array is as follows:
```python
arr[start:end:step]
```

- `start`: The starting index of the slice (inclusive). If omitted, it defaults to 0.
- `end`: The ending index of the slice (exclusive). If omitted, it defaults to the length of the array.
- `step`: The step size or stride of the slice. It determines the increment between each element in the slice. If omitted, it defaults to 1.

### <a id='toc2_2_'></a>[Slicing Single-dimensional Arrays](#toc0_)


Let's consider an example of slicing a single-dimensional array:


In [20]:
arr = np.array([1, 2, 3, 4, 5])

To extract a slice from index 1 to index 3 (exclusive), you can use:


In [21]:
arr[1:4]

array([2, 3, 4])

This returns a new array `[2, 3, 4]`.


If you omit the starting index, it defaults to 0:


In [22]:
arr[:3]

array([1, 2, 3])

This returns `[1, 2, 3]`.


Similarly, if you omit the ending index, it defaults to the length of the array:


In [23]:
arr[2:]

array([3, 4, 5])

This returns `[3, 4, 5]`.


You can also use negative indices in slicing:


In [24]:
arr[-3:]

array([3, 4, 5])

This returns `[3, 4, 5]`, extracting the last three elements of the array.


### <a id='toc2_3_'></a>[Slicing Multi-dimensional Arrays](#toc0_)


Slicing multi-dimensional arrays follows a similar syntax, but you need to provide slicing parameters for each dimension. Let's consider an example:


In [25]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])

To extract a slice that includes the first two rows and the first two columns, you can use:


In [26]:
arr_2d[:2, :2]

array([[1, 2],
       [4, 5]])

You can also mix and match slicing with individual indices:


In [27]:
arr_2d[1:, 1]

array([5, 8])

This returns `[5, 8]`, extracting elements from the second row onwards and the second column.


### <a id='toc2_4_'></a>[Slicing with Step Size](#toc0_)


You can specify a step size in slicing to skip elements in the slice. The step size determines the increment between each element in the slice. Let's consider an example:


In [28]:
arr = np.array([1, 2, 3, 4, 5])

To extract every other element from the array, you can use:


In [29]:
arr[::2]

array([1, 3, 5])

This returns `[1, 3, 5]`, selecting elements with a step size of 2.


You can also use a negative step size to reverse the order of elements in the slice:


In [30]:
arr[::-1]

array([5, 4, 3, 2, 1])

This returns `[5, 4, 3, 2, 1]`, reversing the array.


Slicing with step size can be applied to multi-dimensional arrays as well:


In [31]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
arr_2d[::2, ::2]

array([[1, 3],
       [7, 9]])

It selects every other row and every other column from the array.


Slicing provides a flexible and efficient way to extract subsets of elements from NumPy arrays. It allows you to select contiguous sections of an array, skip elements using step size, and even reverse the order of elements.


In the next section, we'll explore advanced indexing techniques, such as boolean indexing and fancy indexing, which offer even more powerful ways to select elements from arrays based on conditions and arbitrary index arrays.

## <a id='toc3_'></a>[Advanced Indexing Techniques](#toc0_)

In addition to basic indexing and slicing, NumPy provides advanced indexing techniques that allow you to select elements from arrays based on conditions and arbitrary index arrays. In this section, we'll explore boolean indexing, fancy indexing, and how to combine indexing and slicing.


### <a id='toc3_1_'></a>[Boolean Indexing](#toc0_)


Boolean indexing allows you to select elements from an array based on a boolean condition. You can create a boolean mask array of the same shape as the original array, where each element is either `True` or `False`. When you use this boolean mask to index the array, only the elements corresponding to `True` values are selected.


Here's an example:


In [32]:
arr = np.array([1, 2, 3, 4, 5])
mask = np.array([True, False, True, False, True])
result = arr[mask]
result

array([1, 3, 5])

In this case, the boolean mask `mask` selects the elements at indices 0, 2, and 4 from `arr`.


You can also create boolean masks using comparison operators:


In [33]:
arr = np.array([1, 2, 3, 4, 5])
result = arr[arr > 3]
result

array([4, 5])

Here, the condition `arr > 3` creates a boolean mask that selects elements greater than 3 from `arr`.


Boolean indexing is useful when you want to filter an array based on a condition or select elements that satisfy a specific criteria.


### <a id='toc3_2_'></a>[Fancy Indexing](#toc0_)


Fancy indexing allows you to select elements from an array using an array of indices. You can provide an array of integers specifying the indices you want to select.


Here's an example:


In [34]:
arr = np.array([10, 20, 30, 40, 50])
indices = np.array([1, 3, 4])
result = arr[indices]
result

array([20, 40, 50])

In this case, the array `indices` specifies the indices 1, 3, and 4, and fancy indexing selects the corresponding elements from `arr`.


Fancy indexing can also be used with multi-dimensional arrays:


In [35]:
arr_2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
row_indices = np.array([0, 1, 2])
col_indices = np.array([1, 2, 0])
result = arr_2d[row_indices, col_indices]
result

array([2, 6, 7])

Here, `row_indices` and `col_indices` specify the row and column indices to select, respectively. The resulting array contains the elements at the corresponding row and column indices.


Fancy indexing is useful when you want to select elements from an array based on a set of arbitrary indices.


### <a id='toc3_3_'></a>[Combining Indexing and Slicing](#toc0_)


You can combine indexing and slicing techniques to select specific subsets of an array. This allows you to use basic indexing, slicing, boolean indexing, and fancy indexing together to extract the desired elements.


Here are a few examples:


In [36]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result1 = arr[1:, [0, 2]]
result1

array([[4, 6],
       [7, 9]])

In this case, `1:` selects the second and third rows, and `[0, 2]` selects the first and third columns using fancy indexing.


In [37]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
result2 = arr[arr[:, 1] > 3, 1:]
result2

array([[5, 6],
       [8, 9]])

Here, `arr[:, 1] > 3` creates a boolean mask that selects rows where the second column is greater than 3, and `1:` selects the second and third columns.


Combining indexing and slicing techniques provides flexibility in selecting specific subsets of an array based on various conditions and criteria.


Advanced indexing techniques, such as boolean indexing and fancy indexing, along with the ability to combine them with basic indexing and slicing, offer powerful ways to select and manipulate elements in NumPy arrays.


In the next section, we'll explore how to modify arrays using indexing and slicing, allowing you to update specific elements or subsets of an array.

## <a id='toc4_'></a>[Modifying Arrays using Indexing and Slicing](#toc0_)

Indexing and slicing not only allow you to access elements from arrays but also provide a way to modify specific elements or subsets of an array. In this section, we'll explore how to assign values to array elements and modify slices of an array.


### <a id='toc4_1_'></a>[Assigning Values to Array Elements](#toc0_)


You can use indexing to assign new values to specific elements of an array. By specifying the index or indices of the elements you want to modify, you can update their values.


Here's an example:


In [38]:
arr = np.array([1, 2, 3, 4, 5])

In [39]:
arr[2] = 10
arr

array([ 1,  2, 10,  4,  5])

In this case, we assign the value `10` to the element at index 2 of `arr`, modifying the original array.


You can also assign values to multiple elements using an array of indices:


In [40]:
arr = np.array([1, 2, 3, 4, 5])

In [41]:
indices = np.array([0, 2, 4])
arr[indices] = 0
arr

array([0, 2, 0, 4, 0])

Here, we use an array of indices `indices` to specify the elements we want to modify, and we assign the value `0` to those elements.


When assigning values to array elements, it's important to ensure that the shape of the assigned value matches the shape of the indexed portion of the array. If there is a mismatch, NumPy will raise an error.


### <a id='toc4_2_'></a>[Modifying Slices of an Array](#toc0_)


Slicing allows you to modify entire subsets of an array at once. You can assign new values to a slice of an array, and the changes will be reflected in the original array.


Here's an example:


In [42]:
arr = np.array([1, 2, 3, 4, 5])

In [43]:
arr[1:4] = 0
arr

array([1, 0, 0, 0, 5])

In this case, we assign the value `0` to the slice `arr[1:4]`, which includes elements at indices 1, 2, and 3. The original array is modified accordingly.


You can also assign an array to a slice, as long as the shape of the assigned array matches the shape of the slice:


In [44]:
arr = np.array([1, 2, 3, 4, 5])

In [45]:
arr[1:4] = [10, 20, 30]
arr

array([ 1, 10, 20, 30,  5])

Here, we assign the array `[10, 20, 30]` to the slice `arr[1:4]`, replacing the corresponding elements in the original array.


When modifying slices of an array, keep in mind that the changes affect the original array. If you want to modify a slice without changing the original array, you need to create a copy of the slice before making the modifications.


Modifying arrays using indexing and slicing provides a convenient way to update specific elements or subsets of an array. It allows you to change values, replace sections of an array, and perform in-place modifications efficiently.


### <a id='toc4_3_'></a>[Views vs. Copies in Slicing](#toc0_)

When you slice a NumPy array, it's important to understand whether the slicing operation returns a view or a copy of the original array. The behavior depends on how the slicing is performed.


<img src="./images/view-copy.png" width="800">

#### <a id='toc4_3_1_'></a>[Views](#toc0_)


In most cases, slicing a NumPy array returns a view of the original array. A view is a new array object that shares the same underlying data as the original array. Any modifications made to the view will affect the original array, and vice versa. Views are useful when you want to work with a subset of the array without copying the data.


Here's an example:


In [46]:
arr = np.array([1, 2, 3, 4, 5])

In [47]:
view = arr[1:4]

In [48]:
view[0] = 10

In [49]:
view

array([10,  3,  4])

In [50]:
arr

array([ 1, 10,  3,  4,  5])

Output:
```
[1, 10, 3, 4, 5]
```


In this case, `view` is a view of `arr`, and modifying `view` also modifies the corresponding elements in `arr`.


#### <a id='toc4_3_2_'></a>[Copies](#toc0_)


In some cases, slicing a NumPy array returns a copy of the original array. A copy is a new array object with its own separate copy of the data. Modifying the copy does not affect the original array, and vice versa. Copies are useful when you want to work with a subset of the array independently, without modifying the original data.


Here are a few scenarios where slicing returns a copy:

1. When you use an advanced indexing operation, such as boolean indexing or fancy indexing (which we'll cover in the next section), the result is always a copy.

2. When you use a non-contiguous slice, such as `arr[::2]` or `arr[::-1]`, the result is a copy.

3. When you explicitly request a copy using the `copy()` method, like `arr[1:4].copy()`.


Here's an example:


In [51]:
arr = np.array([1, 2, 3, 4, 5])

In [52]:
copy = arr[::2].copy()

In [53]:
copy[0] = 10

In [54]:
copy

array([10,  3,  5])

In [55]:
arr

array([1, 2, 3, 4, 5])

In this case, `copy` is a new array object with its own copy of the data, and modifying `copy` does not affect `arr`.


### <a id='toc4_4_'></a>[Memory Sharing Check](#toc0_)

NumPy provides two functions to check if two arrays share the same memory:

1. `np.may_share_memory(a, b)`: This function returns `True` if the arrays `a` and `b` might share memory, and `False` if they definitely do not share memory. It performs a quick check based on the arrays' memory addresses and dimensions.

2. `np.shares_memory(a, b)`: This function returns `True` if the arrays `a` and `b` actually share memory, and `False` otherwise. It performs a more thorough check by comparing the memory addresses of the arrays' underlying data buffers.


Here's an example that demonstrates the usage of these functions:


In [56]:
a = np.array([1, 2, 3, 4, 5])
b = a[2:4]
c = a.copy()

In [57]:
np.may_share_memory(a, b)

True

In [58]:
np.shares_memory(a, b)

True

In [59]:
np.may_share_memory(a, c)

False

In [60]:
np.shares_memory(a, c)

False

In this example, `b` is a view of `a`, so they share the same memory. Both `np.may_share_memory(a, b)` and `np.shares_memory(a, b)` return `True`.


On the other hand, `c` is a copy of `a`, so they do not share memory. Both `np.may_share_memory(a, c)` and `np.shares_memory(a, c)` return `False`.


Using these functions can be helpful when you want to determine whether modifying one array will affect another array that shares the same memory.

#### <a id='toc4_4_1_'></a>[When to Use Views vs. Copies](#toc0_)


The choice between using views or copies depends on your specific requirements:

- Use views when you want to work with a subset of the array and any modifications should be reflected in the original array. Views are more memory-efficient since they don't create a new copy of the data.

- Use copies when you want to work with a subset of the array independently, without modifying the original data. Copies ensure that the original array remains unchanged.


It's important to be aware of the difference between views and copies to avoid unintended modifications to the original array. If you're unsure whether a slicing operation returns a view or a copy, you can use the `base` attribute to check. If `view.base` is `None`, it means `view` is a copy. If `view.base` is not `None`, it means `view` is a view of the original array.


Understanding the behavior of views and copies in slicing helps you write more precise and predictable code when working with NumPy arrays.

## <a id='toc5_'></a>[Best Practices and Common Pitfalls](#toc0_)

When working with indexing and slicing in NumPy, there are certain best practices to follow and common pitfalls to avoid. In this section, we'll discuss how to avoid out-of-bounds errors, understand the behavior of views vs. copies, and consider performance implications.


### <a id='toc5_1_'></a>[Avoiding Out-of-Bounds Errors](#toc0_)


One common pitfall when using indexing and slicing is trying to access elements that are outside the bounds of the array. This can lead to IndexError exceptions. To avoid out-of-bounds errors, make sure to:

- Use valid indices within the range of the array dimensions.
- Be cautious when using negative indices, ensuring they are within the valid range.
- Be mindful of the array shape when slicing, especially when using multi-dimensional arrays.


Here's an example of an out-of-bounds error:


In [61]:
arr = np.array([1, 2, 3, 4, 5])
arr[10]  # Raises IndexError: index 10 is out of bounds for axis 0 with size 5

IndexError: index 10 is out of bounds for axis 0 with size 5

To avoid such errors, you can use techniques like:

- Checking the array shape using the `shape` attribute before accessing elements.
- Using conditional statements to ensure indices are within valid ranges.
- Handling exceptions using `try-except` blocks when necessary.


### <a id='toc5_2_'></a>[Understanding View vs. Copy Behavior](#toc0_)


As discussed earlier, slicing can return either a view or a copy of the original array, depending on how the slicing is performed. It's important to understand this behavior to avoid unintended modifications to the original array.


Here are some best practices:

- Be aware that basic slicing (e.g., `arr[start:end]`) typically returns a view, while advanced indexing (e.g., boolean indexing, fancy indexing) returns a copy.
- If you want to ensure that modifications to the sliced array do not affect the original array, explicitly create a copy using the `copy()` method.
- Use views when you want to work with a subset of the array and have modifications reflected in the original array, as views are more memory-efficient.


Example of creating an explicit copy:


In [62]:
arr = np.array([1, 2, 3, 4, 5])
sliced_arr = arr[1:4].copy()
sliced_arr[0] = 10
arr  # Original array remains unchanged

array([1, 2, 3, 4, 5])

By creating an explicit copy using `copy()`, modifications to `sliced_arr` do not affect the original array `arr`.


### <a id='toc5_3_'></a>[Performance Considerations](#toc0_)


Indexing and slicing can have performance implications, especially when working with large arrays. Here are a few performance considerations to keep in mind:

- Accessing elements using basic indexing and slicing is generally fast, as NumPy arrays are stored in contiguous memory blocks.
- Advanced indexing techniques, such as boolean indexing and fancy indexing, can be slower compared to basic indexing and slicing because they involve creating new arrays.
- When possible, use basic slicing instead of advanced indexing for better performance.
- Be mindful of the size of the arrays you are working with. Slicing large arrays can create new large arrays, consuming memory.
- If you need to perform repeated operations on a subset of an array, consider extracting that subset into a separate array to avoid repeated slicing.


Example of extracting a subset into a separate array:


In [63]:
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
subset = arr[1:, 1:]  # Extract the subset into a separate array
result = subset ** 2  # Perform operations on the subset

By extracting the subset into a separate array `subset`, you can perform operations on it directly, avoiding repeated slicing of the original array.


Following these best practices and being aware of the common pitfalls can help you write more efficient and error-free code when working with indexing and slicing in NumPy.


Remember, the key is to understand the behavior of indexing and slicing operations, use them appropriately based on your requirements, and consider the performance implications, especially when dealing with large arrays.

<img src="../images/exercise-banner.gif" width="800">

## <a id='toc6_'></a>[Practice Exercise: Analyzing Temperature Data](#toc0_)

You are given a NumPy array `temperatures` that contains the daily temperature readings for a city over a period of one week. The array has shape `(7, 24)`, representing 7 days and 24 hourly temperature readings per day.


In [64]:
import numpy as np

temperatures = np.array([[12, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24,
                          23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12],
                         [13, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25,
                          24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13],
                         [14, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
                          25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14],
                         [15, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27,
                          26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15],
                         [16, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28,
                          27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16],
                         [17, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29,
                          28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17],
                         [18, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30,
                          29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18]])

Your task is to perform the following operations using indexing and slicing:

1. Extract the temperature readings for the first day.
2. Extract the temperature readings for the last day.
3. Extract the temperature readings for the first 12 hours of each day.
4. Extract the temperature readings for the last 6 hours of each day.
5. Extract the temperature readings for every other hour of the fourth day.
6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher.
7. Create a boolean mask to find all temperature readings above 25 degrees.


### <a id='toc6_1_'></a>[Solution](#toc0_)


1. Extract the temperature readings for the first day:

In [65]:
first_day = temperatures[0, :]
print("Temperature readings for the first day:\n", first_day)

Temperature readings for the first day:
 [12 14 15 16 17 18 19 20 21 22 23 24 23 22 21 20 19 18 17 16 15 14 13 12]


2. Extract the temperature readings for the last day:

In [66]:
last_day = temperatures[-1, :]
print("Temperature readings for the last day:\n", last_day)

Temperature readings for the last day:
 [18 20 21 22 23 24 25 26 27 28 29 30 29 28 27 26 25 24 23 22 21 20 19 18]


3. Extract the temperature readings for the first 12 hours of each day:

In [67]:
first_12_hours = temperatures[:, :12]
print("Temperature readings for the first 12 hours of each day:\n", first_12_hours)

Temperature readings for the first 12 hours of each day:
 [[12 14 15 16 17 18 19 20 21 22 23 24]
 [13 15 16 17 18 19 20 21 22 23 24 25]
 [14 16 17 18 19 20 21 22 23 24 25 26]
 [15 17 18 19 20 21 22 23 24 25 26 27]
 [16 18 19 20 21 22 23 24 25 26 27 28]
 [17 19 20 21 22 23 24 25 26 27 28 29]
 [18 20 21 22 23 24 25 26 27 28 29 30]]


4. Extract the temperature readings for the last 6 hours of each day:

In [68]:
last_6_hours = temperatures[:, -6:]
print("Temperature readings for the last 6 hours of each day:\n", last_6_hours)

Temperature readings for the last 6 hours of each day:
 [[17 16 15 14 13 12]
 [18 17 16 15 14 13]
 [19 18 17 16 15 14]
 [20 19 18 17 16 15]
 [21 20 19 18 17 16]
 [22 21 20 19 18 17]
 [23 22 21 20 19 18]]


5. Extract the temperature readings for every other hour of the fourth day:

In [69]:
fourth_day_every_other_hour = temperatures[3, ::2]
print("Temperature readings for every other hour of the fourth day:\n", fourth_day_every_other_hour)

Temperature readings for every other hour of the fourth day:
 [15 18 20 22 24 26 26 24 22 20 18 16]


6. Modify the temperature readings for the first 3 hours of the fifth day to be 10 degrees higher:

In [70]:
temperatures[4, :3] += 10
print("Modified temperature readings for the first 3 hours of the fifth day:\n", temperatures[4, :])

Modified temperature readings for the first 3 hours of the fifth day:
 [26 28 29 20 21 22 23 24 25 26 27 28 27 26 25 24 23 22 21 20 19 18 17 16]


7. Create a boolean mask to find all temperature readings above 25 degrees:

In [71]:
above_25_mask = temperatures > 25
print("Boolean mask for temperature readings above 25 degrees:\n", above_25_mask)

Boolean mask for temperature readings above 25 degrees:
 [[False False False False False False False False False False False False
  False False False False False False False False False False False False]
 [False False False False False False False False False False False False
  False False False False False False False False False False False False]
 [False False False False False False False False False False False  True
  False False False False False False False False False False False False]
 [False False False False False False False False False False  True  True
   True False False False False False False False False False False False]
 [ True  True  True False False False False False False  True  True  True
   True  True False False False False False False False False False False]
 [False False False False False False False False  True  True  True  True
   True  True  True False False False False False False False False False]
 [False False False False False False False  True

In [72]:
above_25_temperatures = temperatures[above_25_mask]
print("Temperature readings above 25 degrees:\n", above_25_temperatures)

Temperature readings above 25 degrees:
 [26 26 27 26 26 28 29 26 27 28 27 26 26 27 28 29 28 27 26 26 27 28 29 30
 29 28 27 26]


In this exercise, we used various indexing and slicing techniques to analyze the temperature data. We extracted specific days, hours, and subsets of the data using square bracket notation and slicing syntax. We also modified specific elements of the array and created a boolean mask to find temperature readings above a certain threshold.


Feel free to modify the temperature data array and experiment with different indexing and slicing operations to further practice and reinforce your understanding of these concepts in NumPy.